"""The whole design language in one static stylesheet.
Colour encodes outcome (done / missed); the blue line is the only glowing
spine; chrome stays cold slate. Motion is pure CSS so it survives
Streamlit's no-JS markdown sandbox. Mobile: every Streamlit column stack
collapses to one column under 760px and the grids tighten.
"""

CSS = (
"@import url('https://fonts.googleapis.com/css2"
"?family=Space+Grotesk:wght@400;500;600;700&display=swap');\n"
"@import url('https://fonts.googleapis.com/css2"
"?family=Manrope:wght@400;500;600;700;800&display=swap');\n"
"@import url('https://fonts.googleapis.com/css2"
"?family=JetBrains+Mono:wght@400;500;600;700&display=swap');\n"
":root{"
"--canvas:#070B14;--panel:#0E1422;--panel-2:#121A2B;"
"--hair:#1C2740;--hair-2:#2A3858;--ink:#E8EDF7;--ink-2:#B6C0D4;"
"--mute:#69748C;--win:#34D399;--win-soft:rgba(52,211,153,.14);"
"--loss:#F0556B;--loss-soft:rgba(240,85,107,.14);"
"--accent:#4C8DFF;--accent-soft:rgba(76,141,255,.16);"
"--jewel:#D946EF;"
"--disp:'Space Grotesk',system-ui,sans-serif;"
"--body:'Manrope',system-ui,sans-serif;"
"--mono:'JetBrains Mono',ui-monospace,monospace;}\n"
"html,body,.stApp{background:var(--canvas);color:var(--ink);"
"font-family:var(--body);}\n"
".stApp{overflow-x:hidden;}\n"
".stApp::before{content:'';position:fixed;inset:0;z-index:0;"
"pointer-events:none;background:"
"radial-gradient(900px 520px at 8% -8%,"
"rgba(76,141,255,.10),transparent 62%),"
"radial-gradient(820px 520px at 97% 2%,"
"rgba(52,211,153,.06),transparent 62%),"
"radial-gradient(760px 640px at 84% 106%,"
"rgba(217,70,239,.05),transparent 62%);"
"animation:tw-drift 26s ease-in-out infinite alternate;}\n"
".stApp::after{content:'';position:fixed;inset:0;z-index:0;"
"pointer-events:none;background-image:"
"linear-gradient(rgba(255,255,255,.022) 1px,transparent 1px),"
"linear-gradient(90deg,rgba(255,255,255,.022) 1px,transparent 1px);"
"background-size:46px 46px;"
"-webkit-mask-image:radial-gradient(circle at 50% 22%,"
"#000 0%,transparent 82%);"
"mask-image:radial-gradient(circle at 50% 22%,"
"#000 0%,transparent 82%);}\n"
"@keyframes tw-drift{0%{transform:translate3d(0,0,0) scale(1);}"
"100%{transform:translate3d(-1.4%,-1%,0) scale(1.05);}}\n"
".block-container{position:relative;z-index:1;"
"padding-top:1.3rem;padding-bottom:3rem;max-width:1560px;}\n"
"footer{display:none!important;}#MainMenu{opacity:.5;}\n"
".tw-win{color:var(--win)!important;}"
".tw-loss{color:var(--loss)!important;}"
".tw-ink{color:var(--ink)!important;}"
".tw-accent{color:var(--accent)!important;}"
".tw-mute{color:var(--mute)!important;}"
".tw-jewel{color:var(--jewel)!important;}\n"
"@keyframes tw-rise{from{opacity:0;transform:translateY(14px);}"
"to{opacity:1;transform:none;}}\n"
"@keyframes tw-draw{from{stroke-dashoffset:6000;}"
"to{stroke-dashoffset:0;}}\n"
"@keyframes tw-fade{from{opacity:0;}to{opacity:1;}}\n"
"@keyframes tw-grow{from{transform:scaleX(0);}"
"to{transform:scaleX(1);}}\n"
"@keyframes tw-growY{from{transform:scaleY(0);}"
"to{transform:scaleY(1);}}\n"
"@keyframes tw-pulse{0%{box-shadow:0 0 0 0 rgba(52,211,153,.5);}"
"70%{box-shadow:0 0 0 7px rgba(52,211,153,0);}"
"100%{box-shadow:0 0 0 0 rgba(52,211,153,0);}}\n"
"@keyframes tw-pulse2{0%{box-shadow:0 0 0 0 var(--accent);}"
"70%{box-shadow:0 0 0 8px transparent;}"
"100%{box-shadow:0 0 0 0 transparent;}}\n"
".tw-greet{display:flex;align-items:center;gap:.55rem;"
"padding:.3rem 0 .1rem;}\n"
".tw-greet-hi{font:500 15px/1 var(--body);color:var(--mute);}\n"
".tw-greet-name{font:700 22px/1 var(--disp);color:var(--ink);"
"letter-spacing:-.01em;}\n"
".tw-live{width:8px;height:8px;border-radius:50%;"
"background:var(--win);display:inline-block;"
"animation:tw-pulse 2s infinite;margin-left:.2rem;}\n"
".tw-panel{background:linear-gradient(180deg,var(--panel),"
"var(--panel-2));border:1px solid var(--hair);border-radius:12px;"
"padding:16px 18px;"
"animation:tw-rise .55s cubic-bezier(.2,.7,.2,1) both;}\n"
".tw-panel-h{display:flex;align-items:center;"
"justify-content:space-between;margin-bottom:12px;gap:8px;}\n"
".tw-panel-t{font:600 11px/1 var(--disp);letter-spacing:.16em;"
"text-transform:uppercase;color:var(--mute);}\n"
".tw-pill{font:600 11px/1 var(--mono);color:var(--ink-2);"
"background:rgba(255,255,255,.04);border:1px solid var(--hair);"
"border-radius:999px;padding:5px 10px;white-space:nowrap;}\n"
".tw-tiles{display:grid;gap:12px;}\n"
".tw-tile{background:linear-gradient(180deg,var(--panel),"
"var(--panel-2));border:1px solid var(--hair);border-radius:12px;"
"padding:14px 16px;"
"animation:tw-rise .5s cubic-bezier(.2,.7,.2,1) both;transition:.2s;}\n"
".tw-tile:hover{transform:translateY(-3px);"
"border-color:var(--hair-2);"
"box-shadow:0 12px 30px -18px rgba(0,0,0,.8);}\n"
".tw-tile-top{display:flex;align-items:center;"
"justify-content:space-between;margin-bottom:10px;gap:6px;}\n"
".tw-lab{font:600 10px/1 var(--disp);letter-spacing:.14em;"
"text-transform:uppercase;color:var(--mute);}\n"
".tw-chip{width:28px;height:28px;border-radius:8px;display:grid;"
"place-items:center;background:var(--accent-soft);"
"color:var(--accent);flex:0 0 auto;}\n"
".tw-chip svg{width:15px;height:15px;display:block;}\n"
".tw-chip.tw-win{background:var(--win-soft);}"
".tw-chip.tw-loss{background:var(--loss-soft);}"
".tw-chip.tw-jewel{background:rgba(217,70,239,.14);}\n"
".tw-val{font:700 27px/1.05 var(--mono);color:var(--ink);"
"font-variant-numeric:tabular-nums;letter-spacing:-.02em;}\n"
".tw-sub{font:600 11px/1 var(--mono);color:var(--mute);"
"margin-top:7px;font-variant-numeric:tabular-nums;}\n"
".tw-tagc{display:inline-block;font:700 9px/1 var(--mono);"
"letter-spacing:.08em;text-transform:uppercase;padding:3px 8px;"
"border-radius:999px;}\n"
".tw-badge{display:inline-block;font:700 9px/1 var(--mono);"
"letter-spacing:.08em;text-transform:uppercase;padding:4px 9px;"
"border-radius:999px;border:1px solid var(--hair);white-space:nowrap;}\n"
".tw-prog{height:9px;background:rgba(255,255,255,.05);"
"border-radius:5px;overflow:hidden;margin:10px 0 6px;}\n"
".tw-prog-fill{height:100%;border-radius:5px;transform-origin:left;"
"animation:tw-grow .9s ease both;}\n"
".tw-now{display:grid;grid-template-columns:1.25fr .75fr;"
"gap:22px;align-items:center;}\n"
".tw-now-lab{font:700 11px/1 var(--disp);letter-spacing:.22em;"
"color:var(--accent);}\n"
".tw-now-block{font:700 30px/1.05 var(--disp);color:var(--ink);"
"margin:9px 0 2px;}\n"
".tw-now-meta{margin:8px 0 2px;}\n"
".tw-now-time{font:700 42px/1 var(--mono);color:var(--ink);"
"letter-spacing:-.03em;}\n"
".tw-now-bar{height:8px;background:rgba(255,255,255,.05);"
"border-radius:5px;overflow:hidden;margin:14px 0 8px;}\n"
".tw-now-fill{height:100%;background:linear-gradient(90deg,"
"var(--accent),var(--win));transform-origin:left;"
"animation:tw-grow 1s ease both;}\n"
".tw-now-next{font:500 12px/1 var(--mono);color:var(--mute);}\n"
".tw-tl{display:flex;flex-direction:column;}\n"
".tw-tl-item{display:grid;grid-template-columns:54px 20px 1fr;"
"gap:12px;position:relative;padding:7px 6px;border-radius:10px;"
"transition:.18s;}\n"
".tw-tl-item:hover{background:rgba(255,255,255,.025);}\n"
".tw-tl-time{text-align:right;font:600 11px/1 var(--mono);"
"color:var(--mute);padding-top:3px;}\n"
".tw-tl-rail{position:relative;display:flex;"
"justify-content:center;}\n"
".tw-tl-rail::before{content:'';position:absolute;top:0;bottom:0;"
"width:2px;background:var(--hair);}\n"
".tw-tl-item:first-child .tw-tl-rail::before{top:50%;}\n"
".tw-tl-item:last-child .tw-tl-rail::before{bottom:50%;}\n"
".tw-tl-dot{position:relative;z-index:1;width:11px;height:11px;"
"border-radius:50%;margin-top:3px;background:var(--panel-2);"
"border:2px solid var(--hair-2);}\n"
".tw-tl-label{font:600 13px/1.2 var(--body);color:var(--ink-2);}\n"
".tw-tl-meta{margin-top:5px;}\n"
".tw-tl-item.done .tw-tl-dot{background:var(--win);"
"border-color:var(--win);}\n"
".tw-tl-item.done .tw-tl-rail::before{background:rgba(52,211,153,.35);}\n"
".tw-tl-item.done .tw-tl-label,"
".tw-tl-item.done .tw-tl-time{color:var(--mute);}\n"
".tw-tl-item.active{background:linear-gradient(90deg,"
"var(--accent-soft),transparent);}\n"
".tw-tl-item.active .tw-tl-dot{background:var(--accent);"
"border-color:var(--accent);animation:tw-pulse2 2s infinite;}\n"
".tw-tl-item.active .tw-tl-label{color:var(--ink);font-weight:800;}\n"
".tw-hhead,.tw-hgrid{display:grid;"
"grid-template-columns:150px 1fr 44px;gap:6px 10px;"
"align-items:center;}\n"
".tw-hhead-days{display:grid;gap:3px;}\n"
".tw-hhead-days span{font:500 8px/1 var(--mono);color:var(--mute);"
"text-align:center;}\n"
".tw-hrow-name{display:flex;align-items:center;gap:8px;"
"font:600 12px/1 var(--body);color:var(--ink-2);}\n"
".tw-hrow-ico{width:18px;height:18px;border-radius:5px;"
"display:grid;place-items:center;font:700 10px/1 var(--mono);"
"color:var(--accent);background:var(--accent-soft);flex:0 0 auto;}\n"
".tw-hcells{display:grid;gap:3px;}\n"
".tw-hcell{height:16px;border-radius:3px;border:1px solid var(--hair);"
"background:rgba(255,255,255,.02);transition:.15s;}\n"
".tw-hcell:hover{transform:scale(1.25);}\n"
".tw-hcell.done{background:var(--win);border-color:transparent;"
"opacity:.85;}\n"
".tw-hcell.miss{background:rgba(240,85,107,.5);"
"border-color:transparent;}\n"
".tw-hcell.today{box-shadow:inset 0 0 0 1.5px var(--accent);}\n"
".tw-hcell.future{opacity:.22;}\n"
".tw-hpct{font:700 11px/1 var(--mono);text-align:right;"
"font-variant-numeric:tabular-nums;}\n"
".tw-goal{border:1px solid var(--hair);border-radius:12px;"
"padding:14px 16px;background:linear-gradient(180deg,var(--panel),"
"var(--panel-2));animation:tw-rise .5s ease both;transition:.2s;"
"margin-bottom:10px;}\n"
".tw-goal:hover{border-color:var(--hair-2);transform:translateY(-2px);}\n"
".tw-goal-t{font:700 14px/1.2 var(--disp);color:var(--ink);}\n"
".tw-goal-m{font:600 11px/1 var(--mono);color:var(--mute);"
"margin-top:6px;}\n"
".tw-goal-bar{height:8px;background:rgba(255,255,255,.05);"
"border-radius:5px;overflow:hidden;margin:11px 0 7px;}\n"
".tw-goal-fill{height:100%;border-radius:5px;transform-origin:left;"
"animation:tw-grow .9s ease both;}\n"
".tw-goal-foot{display:flex;justify-content:space-between;"
"font:600 11px/1 var(--mono);font-variant-numeric:tabular-nums;}\n"
".tw-cc{border:1px solid var(--hair);border-radius:12px;"
"padding:13px 15px;background:linear-gradient(180deg,var(--panel),"
"var(--panel-2));margin-bottom:10px;"
"animation:tw-rise .5s ease both;transition:.2s;}\n"
".tw-cc:hover{border-color:var(--hair-2);transform:translateY(-2px);}\n"
".tw-cc-top{display:flex;justify-content:space-between;"
"align-items:center;gap:8px;}\n"
".tw-cc-name{font:700 14px/1.2 var(--disp);color:var(--ink);}\n"
".tw-cc-meta{font:600 11px/1 var(--mono);color:var(--mute);"
"margin-top:6px;}\n"
".tw-eq{width:100%;height:auto;display:block;}\n"
".tw-eq-line{fill:none;stroke:var(--accent);stroke-width:2.4;"
"stroke-linecap:round;stroke-linejoin:round;"
"filter:drop-shadow(0 0 6px rgba(76,141,255,.55));"
"stroke-dasharray:6000;animation:tw-draw 1.1s ease-out both;}\n"
".tw-eq-area{animation:tw-fade 1.2s ease-out both;}\n"
".tw-eq-grid{stroke:var(--hair);stroke-width:1;}\n"
".tw-eq-txt{fill:var(--mute);font:500 11px var(--mono);}\n"
".tw-eq-dot{fill:var(--accent);"
"filter:drop-shadow(0 0 6px rgba(76,141,255,.9));}\n"
".tw-eq-ring{fill:none;stroke:var(--accent);stroke-width:2;"
"opacity:.5;animation:tw-pulse2 2s infinite;}\n"
".tw-bars{display:grid;grid-auto-flow:column;grid-auto-columns:1fr;"
"gap:8px;height:200px;align-items:end;}\n"
".tw-bar-col{position:relative;height:100%;display:flex;"
"flex-direction:column;justify-content:center;align-items:center;}\n"
".tw-bar-track{position:relative;width:60%;max-width:30px;"
"height:78%;}\n"
".tw-bar-zero{position:absolute;left:-30%;right:-30%;top:50%;"
"height:1px;background:var(--hair-2);}\n"
".tw-bar-fill{position:absolute;left:0;right:0;border-radius:4px;"
"transform-origin:center;"
"animation:tw-growY .7s cubic-bezier(.2,.7,.2,1) both;transition:.2s;}\n"
".tw-bar-fill:hover{filter:brightness(1.18);}\n"
".tw-bar-up{background:linear-gradient(180deg,var(--win),"
"rgba(52,211,153,.55));bottom:50%;}\n"
".tw-bar-down{background:linear-gradient(0deg,var(--loss),"
"rgba(240,85,107,.55));top:50%;}\n"
".tw-bar-lab{position:absolute;bottom:-20px;font:500 10px/1 var(--mono);"
"color:var(--mute);}\n"
".tw-cal-head,.tw-cal{display:grid;grid-template-columns:repeat(7,1fr);"
"gap:6px;}\n"
".tw-cal-head span{font:600 10px/1 var(--disp);letter-spacing:.1em;"
"color:var(--mute);text-align:center;padding:2px 0;}\n"
".tw-day{min-height:60px;border:1px solid var(--hair);border-radius:8px;"
"padding:7px 8px;background:rgba(255,255,255,.012);transition:.18s;}\n"
".tw-day:hover{border-color:var(--hair-2);"
"background:rgba(255,255,255,.03);}\n"
".tw-day-num{font:600 11px/1 var(--mono);color:var(--mute);}\n"
".tw-day-pnl{font:700 12px/1 var(--mono);margin-top:8px;"
"font-variant-numeric:tabular-nums;}\n"
".tw-day.up{border-color:rgba(52,211,153,.28);"
"background:var(--win-soft);}\n"
".tw-day.down{border-color:rgba(240,85,107,.28);"
"background:var(--loss-soft);}\n"
".tw-day.empty{background:transparent;border-color:transparent;}\n"
".tw-day.today{box-shadow:inset 0 0 0 1.5px var(--accent);}\n"
".tw-day.future{opacity:.32;}\n"
".tw-donut-wrap{display:flex;align-items:center;gap:18px;"
"flex-wrap:wrap;}\n"
".tw-donut-c1{font:700 11px/1 var(--disp);letter-spacing:.12em;"
"fill:var(--mute);text-transform:uppercase;}\n"
".tw-donut-c2{font:700 19px/1 var(--mono);fill:var(--ink);}\n"
".tw-legend{flex:1 1 170px;display:flex;flex-direction:column;gap:9px;"
"min-width:160px;}\n"
".tw-leg-row{display:grid;grid-template-columns:14px 1fr auto auto;"
"gap:8px;align-items:center;}\n"
".tw-leg-dot{width:9px;height:9px;border-radius:50%;}\n"
".tw-leg-name{font:600 12px/1 var(--body);color:var(--ink-2);}\n"
".tw-leg-val{font:600 12px/1 var(--mono);"
"font-variant-numeric:tabular-nums;}\n"
".tw-leg-pct{font:600 11px/1 var(--mono);color:var(--mute);"
"width:38px;text-align:right;}\n"
".tw-streaks{display:grid;gap:12px;}\n"
".tw-streak{border:1px solid var(--hair);border-radius:10px;"
"padding:14px;text-align:center;background:rgba(255,255,255,.012);"
"animation:tw-rise .5s ease both;}\n"
".tw-streak-n{font:700 30px/1 var(--mono);}\n"
".tw-streak-l{font:600 9px/1 var(--disp);letter-spacing:.1em;"
"text-transform:uppercase;color:var(--mute);margin-top:8px;}\n"
".tw-table{width:100%;border-collapse:collapse;"
"font:500 12.5px/1.4 var(--body);}\n"
".tw-table thead th{font:600 10px/1 var(--disp);letter-spacing:.12em;"
"text-transform:uppercase;color:var(--mute);text-align:left;"
"padding:0 12px 10px;border-bottom:1px solid var(--hair);}\n"
".tw-table tbody td{padding:11px 12px;"
"border-bottom:1px solid rgba(28,39,64,.6);"
"font-variant-numeric:tabular-nums;color:var(--ink-2);"
"white-space:nowrap;}\n"
".tw-table tbody tr{transition:.15s;}"
".tw-table tbody tr:hover{background:rgba(255,255,255,.03);}\n"
".tw-table .num{font-family:var(--mono);}\n"
".tw-stat{display:flex;justify-content:space-between;"
"align-items:center;padding:9px 0;gap:10px;"
"border-bottom:1px solid rgba(28,39,64,.55);}\n"
".tw-stat:last-child{border-bottom:none;}\n"
".tw-stat .k{font:500 12px/1 var(--body);color:var(--mute);}\n"
".tw-stat .v{font:700 13px/1 var(--mono);"
"font-variant-numeric:tabular-nums;text-align:right;}\n"
".tw-empty{text-align:center;color:var(--mute);padding:36px 10px;"
"font:500 13px var(--body);}\n"
".tw-scroll{overflow-x:auto;}\n"
".tw-jcard{border:1px solid var(--hair);border-radius:10px;"
"padding:12px 14px;background:rgba(255,255,255,.012);"
"margin-bottom:10px;}\n"
".tw-jcard .d{font:600 11px/1 var(--mono);color:var(--mute);"
"margin-bottom:7px;}\n"
".tw-jcard .row{font:500 12.5px/1.4 var(--body);color:var(--ink-2);"
"margin:3px 0;}\n"
".tw-jcard .row b{color:var(--mute);font-weight:600;}\n"
"[data-testid='stSidebar']{background:linear-gradient(180deg,"
"#0A0F1B,#070B14);border-right:1px solid var(--hair);z-index:2;}\n"
".tw-brand{display:flex;align-items:center;gap:11px;"
"padding:4px 6px 14px;}\n"
".tw-brand-n{font:700 17px/1 var(--disp);letter-spacing:.06em;"
"color:var(--ink);}\n"
".tw-brand-s{font:600 9px/1 var(--disp);letter-spacing:.22em;"
"color:var(--mute);margin-top:5px;}\n"
".tw-user{display:flex;align-items:center;gap:11px;padding:12px 8px;"
"margin-top:8px;border-top:1px solid var(--hair);}\n"
".tw-avatar{width:36px;height:36px;border-radius:10px;display:grid;"
"place-items:center;font:700 13px var(--disp);color:var(--ink);"
"background:linear-gradient(135deg,var(--accent),"
"rgba(52,211,153,.7));}\n"
".tw-user-n{font:600 13px/1.2 var(--body);color:var(--ink);}\n"
".tw-user-r{font:500 11px/1.2 var(--body);color:var(--mute);"
"margin-top:3px;}\n"
"[data-testid='stSidebar'] [data-testid='stRadio']>div{gap:2px;}\n"
"[data-testid='stSidebar'] [data-testid='stRadio'] label{"
"display:flex;align-items:center;gap:.6rem;padding:.6rem .7rem;"
"border-radius:9px;cursor:pointer;color:var(--mute);"
"font:600 13px/1 var(--disp);margin:0;transition:.18s;}\n"
"[data-testid='stSidebar'] [data-testid='stRadio'] label:hover{"
"background:rgba(255,255,255,.04);color:var(--ink);}\n"
"[data-testid='stSidebar'] [data-testid='stRadio'] "
"label:has(input:checked){background:var(--accent-soft);"
"color:var(--ink);box-shadow:inset 2px 0 0 var(--accent);}\n"
"[data-testid='stSidebar'] [data-testid='stRadio'] "
"input[type='radio']{position:absolute;opacity:0;width:0;height:0;}\n"
"[data-testid='stSidebar'] [data-testid='stRadio'] label p{margin:0;}\n"
"[data-testid='stSidebar'] [data-testid='stRadio'] "
"label>div:first-child{display:none;}\n"
".stSelectbox label,.stTextInput label,.stDateInput label,"
".stNumberInput label,.stTimeInput label,.stMultiSelect label,"
".stTextArea label{font:600 10px/1 var(--disp)!important;"
"letter-spacing:.12em;text-transform:uppercase;"
"color:var(--mute)!important;}\n"
"[data-baseweb='select']>div,[data-baseweb='input']>div,"
".stDateInput input,.stNumberInput input,.stTimeInput input,"
".stTextInput input,.stTextArea textarea{background:var(--panel)"
"!important;border:1px solid var(--hair)!important;"
"border-radius:9px!important;color:var(--ink)!important;"
"font-family:var(--mono)!important;}\n"
".stTextArea textarea{font-family:var(--mono)!important;"
"font-size:12.5px!important;}\n"
".stButton>button{background:var(--panel-2);"
"border:1px solid var(--hair-2);color:var(--ink);border-radius:9px;"
"font:600 12px var(--disp);transition:.18s;}\n"
".stButton>button:hover{border-color:var(--accent);"
"box-shadow:0 0 0 3px var(--accent-soft);}\n"
".stButton>button[kind='primary']{background:var(--accent);"
"border-color:var(--accent);color:#04101f;}\n"
"hr{border-color:var(--hair)!important;}\n"
"/* ---- phone layout: stack every Streamlit row, tighten grids ---- */\n"
"@media (max-width:760px){"
".block-container{padding-top:.7rem;padding-bottom:2rem;}\n"
"[data-testid='stHorizontalBlock']{flex-direction:column!important;"
"gap:.6rem!important;}\n"
"[data-testid='stHorizontalBlock']>div{width:100%!important;"
"flex:1 1 100%!important;}\n"
".tw-tiles{grid-template-columns:repeat(2,1fr)!important;}\n"
".tw-now{grid-template-columns:1fr!important;gap:12px;}\n"
".tw-hhead,.tw-hgrid{grid-template-columns:96px 1fr 38px!important;}\n"
".tw-hrow-name{font-size:10px;}\n"
".tw-hcell{height:12px;}\n"
".tw-day{min-height:44px;padding:4px 5px;}\n"
".tw-day-pnl{font-size:9px;margin-top:5px;}\n"
".tw-now-time{font-size:32px;}\n"
".tw-now-block{font-size:22px;}\n"
".tw-val{font-size:21px;}\n"
".tw-greet-name{font-size:18px;}\n"
".tw-donut-wrap{justify-content:center;}\n"
".tw-tl-item{grid-template-columns:44px 18px 1fr;gap:8px;}\n"
"}\n"
)
